"""Domain scaffolding for creating new domains."""

from pathlib import Path


def scaffold_domain(name: str, location: Path) -> list[Path]:
    """Create a new domain scaffold with all required files.

    Args:
        name: Domain name (lowercase, no spaces).
        location: Parent directory where the domain folder will be created.

    Returns:
        List of created file paths.
    """
    domain_dir = location / name
    templates_dir = domain_dir / "templates"

    # Create directories
    domain_dir.mkdir(parents=True, exist_ok=True)
    templates_dir.mkdir(exist_ok=True)

    created_files: list[Path] = []

    # __init__.py
    init_content = f'''"""The {name} domain for embgen."""

from .generator import {name.capitalize()}Generator

generator = {name.capitalize()}Generator()
'''
    (domain_dir / "__init__.py").write_text(init_content)
    created_files.append(domain_dir / "__init__.py")

    # models.py
    models_content = f'''"""Data models for the {name} domain."""

from embgen.models import BaseConfig


class {name.capitalize()}Config(BaseConfig):
    """Configuration for {name} generation.

    Customize this model with fields specific to your domain.
    Example YAML:
        name: My{name.capitalize()}
        file: my{name}  # optional output filename
        # Add your domain-specific fields here
    """

    # Add your domain-specific fields here
    # Example:
    # description: str | None = None
    # items: list[str] = []
'''
    (domain_dir / "models.py").write_text(models_content)
    created_files.append(domain_dir / "models.py")

    # generator.py
    generator_content = f'''"""Generator implementation for the {name} domain."""

from pathlib import Path
from typing import Any, cast

from jinja2 import Template

from embgen.models import BaseConfig
from embgen.domains import DomainGenerator
from .models import {name.capitalize()}Config


class {name.capitalize()}Generator(DomainGenerator):
    """Generator for {name} domain."""

    @property
    def name(self) -> str:
        return "{name}"

    @property
    def description(self) -> str:
        return "Generate {name} outputs"

    def detect(self, data: dict[str, Any]) -> bool:
        """Detect if YAML data belongs to this domain.

        Customize this method to detect your domain's YAML structure.
        """
        # Example: check for a specific key
        return "{name}" in data or data.get("domain") == "{name}"

    def validate(self, data: dict[str, Any]) -> BaseConfig:
        """Parse and validate YAML into domain config."""
        return cast(BaseConfig, {name.capitalize()}Config.model_validate(data))

    def render(self, config: Any, template: Template) -> str:
        """Render config to a template."""
        cfg: {name.capitalize()}Config = config if isinstance(config, {name.capitalize()}Config) else {name.capitalize()}Config.model_validate(config)
        return template.render(config=cfg)

    @property
    def templates_path(self) -> Path:
        """Path to this domain's templates."""
        return Path(__file__).parent / "templates"

    def post_generate(
        self, config: BaseConfig, output: Path, generated_extensions: set[str]
    ) -> list[str]:
        """Optional: copy extra files after generation.

        Customize to copy additional files if needed.
        """
        return []
'''
    (domain_dir / "generator.py").write_text(generator_content)
    created_files.append(domain_dir / "generator.py")

    # Template files
    template_h = f"""// {{{{ config.name }}}} - Generated by embgen
// DO NOT EDIT - This file is auto-generated

#ifndef {{{{ config.output_filename | upper }}}}_H
#define {{{{ config.output_filename | upper }}}}_H

// Add your {name} domain header content here

#endif // {{{{ config.output_filename | upper }}}}_H
"""
    (templates_dir / "template.h.j2").write_text(template_h)
    created_files.append(templates_dir / "template.h.j2")

    template_py = f'''"""{{{{ config.name }}}} - Generated by embgen.

DO NOT EDIT - This file is auto-generated.
"""

# Add your {name} domain Python content here
'''
    (templates_dir / "template.py.j2").write_text(template_py)
    created_files.append(templates_dir / "template.py.j2")

    template_md = f"""# {{{{ config.name }}}}

> Generated by embgen - DO NOT EDIT

Add your {name} domain Markdown documentation here.
"""
    (templates_dir / "template.md.j2").write_text(template_md)
    created_files.append(templates_dir / "template.md.j2")

    return created_files
