"""
Copyright (C) 2025 ETH Zurich. All rights reserved.

Author: Cedric Hirschi, ETH Zurich
        Sergei Vostrikov, ETH Zurich

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

This file is auto-generated by embgen. Do not edit manually.
"""

from dataclasses import dataclass, fields
import struct
from typing import ClassVar
from enum import Enum


ENDIANNESS = "<"  # Little-endian
HEADER = "BH"  # Command ID (1 byte) + Size (2 bytes)


@dataclass
class Command:
    _id: ClassVar[int]
    _description: ClassVar[str] = ""
    _format: ClassVar[str]

    def pack(self) -> bytes:
        args = fields(self)
        args = filter(lambda arg: not arg.name.startswith("_"), args)
        args = [getattr(self, arg.name) for arg in args]
        args = [arg.value if isinstance(arg, Enum) else arg for arg in args]

        # Get size of the arguments
        args_size = struct.calcsize(ENDIANNESS + self._format)
        return struct.pack(
            ENDIANNESS + HEADER + self._format, self._id, args_size, *args
        )
