"""
Copyright (C) 2025 ETH Zurich. All rights reserved.

Author: Cedric Hirschi, ETH Zurich
        Sergei Vostrikov, ETH Zurich

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

This file is auto-generated by embgen. Do not edit manually.
"""

from dataclasses import dataclass, fields
import struct
from typing import ClassVar
from enum import Enum


ENDIANNESS = "<"  # Little-endian
HEADER = "BH"  # Command ID (1 byte) + Size (2 bytes)


@dataclass
class Command:
    _id: ClassVar[int]
    _description: ClassVar[str] = ""
    _format: ClassVar[str]

    def pack(self) -> bytes:
        args = fields(self)
        args = filter(lambda arg: not arg.name.startswith("_"), args)
        args = [getattr(self, arg.name) for arg in args]
        args = [arg.value if isinstance(arg, Enum) else arg for arg in args]

        # Build a dynamic struct format string so plain 's' becomes a
        # sized bytes field using the actual length of the provided bytes
        fmt = self._format
        out_parts: list[str] = []
        arg_idx = 0
        i = 0
        while i < len(fmt):
            # collect optional numeric repeat count
            num = ""
            while i < len(fmt) and fmt[i].isdigit():
                num += fmt[i]
                i += 1
            if i >= len(fmt):
                break
            code = fmt[i]
            i += 1
            if code == "s":
                # if no explicit count was provided, use the actual length
                if num == "":
                    try:
                        length = len(args[arg_idx])
                    except Exception:
                        length = 0
                    out_parts.append(f"{length}s")
                    arg_idx += 1
                else:
                    out_parts.append(num + "s")
                    arg_idx += 1
            else:
                if num:
                    out_parts.append(num + code)
                    # consume that many args if numeric prefix provided
                    try:
                        arg_idx += int(num)
                    except Exception:
                        arg_idx += 1
                else:
                    out_parts.append(code)
                    arg_idx += 1

        dynamic_format = "".join(out_parts)

        # Get size of the arguments
        args_size = struct.calcsize(ENDIANNESS + dynamic_format)
        return struct.pack(
            ENDIANNESS + HEADER + dynamic_format, self._id, args_size, *args
        )
